package entity

type Status struct {
	AcquBankCd     string `json:"acquBankCd"`
	AcquBankNm     string `json:"acquBankNm"`
	AcquStatus     string `json:"acquStatus"`
	Amt            string `json:"amt"`
	BankCd         string `json:"bankCd"`
	BillingNm      string `json:"billingNm"`
	CancelAmt      string `json:"cancelAmt"`
	CancelTrxSn    string `json:"cancelTrxSn"`
	CardExpYymm    string `json:"cardExpYymm"`
	CardNo         string `json:"cardNo"`
	CcTransType    string `json:"ccTransType"`
	Currency       string `json:"currency"`
	DepositDt      string `json:"depositDt"`
	DepositTm      string `json:"depositTm"`
	GoodsNm        string `json:"goodsNm"`
	IMid           string `json:"iMid"`
	InstmntMon     string `json:"instmntMon"`
	InstmntType    string `json:"instmntType"`
	IssuBankCd     string `json:"issuBankCd"`
	IssuBankNm     string `json:"issuBankNm"`
	MRefNo         string `json:"mRefNo"`
	MitraCd        string `json:"mitraCd"`
	PayMethod      string `json:"payMethod"`
	PayNo          string `json:"payNo"`
	PayValidDt     string `json:"payValidDt"`
	PayValidTm     string `json:"payValidTm"`
	PaymentExpDt   string `json:"paymentExpDt"`
	PaymentExpTm   string `json:"paymentExpTm"`
	PaymentTrxSn   string `json:"paymentTrxSn"`
	PreauthToken   string `json:"preauthToken"`
	ReceiptCode    string `json:"receiptCode"`
	RecurringToken string `json:"recurringToken"`
	ReferenceNo    string `json:"referenceNo"`
	ReqDt          string `json:"reqDt"`
	ReqTm          string `json:"reqTm"`
	ResultCd       string `json:"resultCd"`
	ResultMsg      string `json:"resultMsg"`
	ShopID         string `json:"shopId"`
	Status         string `json:"status"`
	TXid           string `json:"tXid"`
	TransDt        string `json:"transDt"`
	TransTm        string `json:"transTm"`
	UserID         string `json:"userId"`
	VacctNo        string `json:"vacctNo"`
	VacctValidDt   string `json:"vacctValidDt"`
	VacctValidTm   string `json:"vacctValidTm"`
}
